services:
  openapi-generator-online:
    image: openapitools/openapi-generator-online
    ports:
      - "8080:8080"

  ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_MODEL=mistral
      - OLLAMA_WEB_UI_ENABLED=true

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    expose:
      - 8080/tcp
    ports:
      - 8082:8080/tcp
    environment:
      - OLLAMA_API_BASE_URL=http://ollama-container:11434/api
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama-container
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}